#!/bin/sh

set -euo pipefail
notify-send "Building xmonad"
PATH="$PATH:$HOME/.ghcup/bin"
~/.ghcup/bin/cabal install --overwrite-policy=always . || exit 1
rm "$1" || exit 1
ln -s ~/.cabal/bin/xmonad "$1"
notify-send "Built xmonad successfully"
